import { useState, useEffect, useCallback } from "react";
import * as staticData from "@/lib/briefingData";

export type BriefingMeta = {
  generatedAt: string | null;
  isLive: boolean;
  isLoading: boolean;
  error: string | null;
  lastChecked: string | null;
};

// Safely use live data only if it has the required shape; otherwise fall back to static.
// This prevents runtime crashes when Claude returns slightly different structures.
/* eslint-disable @typescript-eslint/no-explicit-any */
function safe<T>(live: any, validator: (v: any) => boolean, fallback: T): T {
  try {
    if (live != null && validator(live)) return live as T;
  } catch { /* shape mismatch */ }
  return fallback;
}

function mergeBriefing(live: Record<string, unknown>) {
  return {
    BRIEFING_DATE: typeof live.briefingDate === "string" ? live.briefingDate : staticData.BRIEFING_DATE,
    BRIEFING_EDITION: typeof live.briefingEdition === "string" ? live.briefingEdition : staticData.BRIEFING_EDITION,
    AI_SUMMARY: safe(live.aiSummary, (v) => typeof v.generatedAt === "string" && Array.isArray(v.paragraphs), staticData.AI_SUMMARY),
    KEY_LEVELS: safe(live.keyLevels, (v) => Array.isArray(v) && v.length > 0 && v[0].symbol && v[0].support, staticData.KEY_LEVELS),
    FEAR_GAUGE: safe(live.fearGauge, (v) => v.vix && v.fearLevel && v.putCallRatio, staticData.FEAR_GAUGE),
    OVERNIGHT_DEVELOPMENTS: safe(live.overnightDevelopments, (v) => Array.isArray(v) && v.length > 0 && v[0].event && v[0].impact, staticData.OVERNIGHT_DEVELOPMENTS),
    CRISIS_STATUS: safe(live.crisisStatus, (v) => v.threatLevel && v.title && Array.isArray(v.indicators) && Array.isArray(v.affectedSectors), staticData.CRISIS_STATUS),
    MARKET_REGIME: safe(live.marketRegime, (v) => v.classification && v.description && Array.isArray(v.bestStrategies), staticData.MARKET_REGIME),
    EXECUTIVE_VIEW: typeof live.executiveView === "string" && live.executiveView.length > 50
      ? (live.executiveView as string)
      : (live.executiveView as any)?.todayPlaybook && typeof (live.executiveView as any).todayPlaybook === "string"
        ? (live.executiveView as any).todayPlaybook
        : staticData.EXECUTIVE_VIEW,
    TRADING_IDEAS: safe(live.tradingIdeas, (v) => Array.isArray(v.today || v.dayTrades) && Array.isArray(v.thisWeek || v.swingTrades), staticData.TRADING_IDEAS),
    SCENARIO_MATRIX: safe(live.scenarioMatrix, (v) => Array.isArray(v) && v.length > 0 && v[0].scenario && v[0].probability != null, staticData.SCENARIO_MATRIX),
    DECISION_SUMMARY: safe(live.decisionSummary, (v) => v.bestOpportunityToday && v.bestSwingIdeaThisWeek && v.biggestRiskToWatch, staticData.DECISION_SUMMARY),
    SECTOR_ROTATION: safe(live.sectorRotation, (v) => Array.isArray(v) && v.length > 0 && v[0].sector, staticData.SECTOR_ROTATION),
    MACRO_CONDITIONS: safe(live.macroConditions, (v) => Array.isArray(v) && v.length > 0 && v[0].indicator, staticData.MACRO_CONDITIONS),
    // These are always static (not generated by AI)
    MARKET_SNAPSHOT: staticData.MARKET_SNAPSHOT,
    NEWS_SIGNALS: staticData.NEWS_SIGNALS,
    SENTIMENT_SUMMARY: staticData.SENTIMENT_SUMMARY,
    EVENT_CALENDAR: staticData.EVENT_CALENDAR,
    SEASONAL_CONTEXT: staticData.SEASONAL_CONTEXT,
    PRIOR_SESSION_GRADES: staticData.PRIOR_SESSION_GRADES,
    EARNINGS_PLAYS: staticData.EARNINGS_PLAYS,
    ACCOUNTS: staticData.ACCOUNTS,
    CROSS_ACCOUNT_RISKS: staticData.CROSS_ACCOUNT_RISKS,
    ACCOUNT_HISTORY: staticData.ACCOUNT_HISTORY,
    ECONOMIC_DATA_BREAKDOWN: staticData.ECONOMIC_DATA_BREAKDOWN,
    WEEKLY_THESIS_SCORECARD: staticData.WEEKLY_THESIS_SCORECARD,
    DEEP_DIVE_TOOLS: staticData.DEEP_DIVE_TOOLS,
  };
}

const STATIC_FALLBACK = mergeBriefing({});

export function useDynamicBriefing() {
  const [data, setData] = useState(STATIC_FALLBACK);
  const [meta, setMeta] = useState<BriefingMeta>({
    generatedAt: staticData.AI_SUMMARY.generatedAt,
    isLive: false,
    isLoading: true,
    error: null,
    lastChecked: null,
  });

  const fetchBriefing = useCallback(async () => {
    try {
      const res = await fetch("/.netlify/functions/get-briefing");
      const contentType = res.headers.get("content-type") || "";
      if (!contentType.includes("application/json")) {
        // Dev server returns HTML for unknown routes — silently use static
        setMeta((prev) => ({
          ...prev,
          isLive: false,
          isLoading: false,
          lastChecked: new Date().toISOString(),
        }));
        return;
      }
      if (!res.ok) {
        if (res.status === 404) {
          setMeta((prev) => ({
            ...prev,
            isLive: false,
            isLoading: false,
            lastChecked: new Date().toISOString(),
          }));
          return;
        }
        throw new Error(`HTTP ${res.status}`);
      }

      const live = await res.json();
      const merged = mergeBriefing(live);
      setData(merged);
      setMeta({
        generatedAt: live._meta?.generatedAt || live.aiSummary?.generatedAt || null,
        isLive: true,
        isLoading: false,
        error: null,
        lastChecked: new Date().toISOString(),
      });
    } catch (err) {
      console.warn("Failed to fetch live briefing, using static fallback:", err);
      setMeta((prev) => ({
        ...prev,
        isLive: false,
        isLoading: false,
        error: err instanceof Error ? err.message : "Unknown error",
        lastChecked: new Date().toISOString(),
      }));
    }
  }, []);

  useEffect(() => {
    fetchBriefing();
    // Refresh every 5 minutes
    const interval = setInterval(fetchBriefing, 5 * 60 * 1000);
    return () => clearInterval(interval);
  }, [fetchBriefing]);

  return { ...data, meta, refreshBriefing: fetchBriefing };
}
