import { useState, useEffect, useCallback } from "react";
import * as staticData from "@/lib/briefingData";

export type BriefingMeta = {
  generatedAt: string | null;
  isLive: boolean;
  isLoading: boolean;
  error: string | null;
  lastChecked: string | null;
};

// Maps API response keys to static export names
function mergeBriefing(live: Record<string, unknown>) {
  return {
    BRIEFING_DATE: (live.briefingDate as string) || staticData.BRIEFING_DATE,
    BRIEFING_EDITION: (live.briefingEdition as string) || staticData.BRIEFING_EDITION,
    AI_SUMMARY: (live.aiSummary as typeof staticData.AI_SUMMARY) || staticData.AI_SUMMARY,
    KEY_LEVELS: (live.keyLevels as typeof staticData.KEY_LEVELS) || staticData.KEY_LEVELS,
    FEAR_GAUGE: (live.fearGauge as typeof staticData.FEAR_GAUGE) || staticData.FEAR_GAUGE,
    OVERNIGHT_DEVELOPMENTS: (live.overnightDevelopments as typeof staticData.OVERNIGHT_DEVELOPMENTS) || staticData.OVERNIGHT_DEVELOPMENTS,
    CRISIS_STATUS: (live.crisisStatus as typeof staticData.CRISIS_STATUS) || staticData.CRISIS_STATUS,
    MARKET_REGIME: (live.marketRegime as typeof staticData.MARKET_REGIME) || staticData.MARKET_REGIME,
    EXECUTIVE_VIEW: live.executiveView
      ? (typeof live.executiveView === "string"
          ? live.executiveView
          : (live.executiveView as { todayPlaybook?: string }).todayPlaybook || staticData.EXECUTIVE_VIEW)
      : staticData.EXECUTIVE_VIEW,
    TRADING_IDEAS: (live.tradingIdeas as typeof staticData.TRADING_IDEAS) || staticData.TRADING_IDEAS,
    SCENARIO_MATRIX: (live.scenarioMatrix as typeof staticData.SCENARIO_MATRIX) || staticData.SCENARIO_MATRIX,
    DECISION_SUMMARY: (live.decisionSummary as typeof staticData.DECISION_SUMMARY) || staticData.DECISION_SUMMARY,
    SECTOR_ROTATION: (live.sectorRotation as typeof staticData.SECTOR_ROTATION) || staticData.SECTOR_ROTATION,
    MACRO_CONDITIONS: (live.macroConditions as typeof staticData.MACRO_CONDITIONS) || staticData.MACRO_CONDITIONS,
    // These are always static (not generated by AI)
    MARKET_SNAPSHOT: staticData.MARKET_SNAPSHOT,
    NEWS_SIGNALS: staticData.NEWS_SIGNALS,
    SENTIMENT_SUMMARY: staticData.SENTIMENT_SUMMARY,
    EVENT_CALENDAR: staticData.EVENT_CALENDAR,
    SEASONAL_CONTEXT: staticData.SEASONAL_CONTEXT,
    PRIOR_SESSION_GRADES: staticData.PRIOR_SESSION_GRADES,
    EARNINGS_PLAYS: staticData.EARNINGS_PLAYS,
    ACCOUNTS: staticData.ACCOUNTS,
    CROSS_ACCOUNT_RISKS: staticData.CROSS_ACCOUNT_RISKS,
    ACCOUNT_HISTORY: staticData.ACCOUNT_HISTORY,
    ECONOMIC_DATA_BREAKDOWN: staticData.ECONOMIC_DATA_BREAKDOWN,
    WEEKLY_THESIS_SCORECARD: staticData.WEEKLY_THESIS_SCORECARD,
    DEEP_DIVE_TOOLS: staticData.DEEP_DIVE_TOOLS,
  };
}

const STATIC_FALLBACK = mergeBriefing({});

export function useDynamicBriefing() {
  const [data, setData] = useState(STATIC_FALLBACK);
  const [meta, setMeta] = useState<BriefingMeta>({
    generatedAt: staticData.AI_SUMMARY.generatedAt,
    isLive: false,
    isLoading: true,
    error: null,
    lastChecked: null,
  });

  const fetchBriefing = useCallback(async () => {
    try {
      const res = await fetch("/.netlify/functions/get-briefing");
      if (!res.ok) {
        if (res.status === 404) {
          // No live briefing yet — use static
          setMeta((prev) => ({
            ...prev,
            isLive: false,
            isLoading: false,
            lastChecked: new Date().toISOString(),
          }));
          return;
        }
        throw new Error(`HTTP ${res.status}`);
      }

      const live = await res.json();
      const merged = mergeBriefing(live);
      setData(merged);
      setMeta({
        generatedAt: live._meta?.generatedAt || live.aiSummary?.generatedAt || null,
        isLive: true,
        isLoading: false,
        error: null,
        lastChecked: new Date().toISOString(),
      });
    } catch (err) {
      console.warn("Failed to fetch live briefing, using static fallback:", err);
      setMeta((prev) => ({
        ...prev,
        isLive: false,
        isLoading: false,
        error: err instanceof Error ? err.message : "Unknown error",
        lastChecked: new Date().toISOString(),
      }));
    }
  }, []);

  useEffect(() => {
    fetchBriefing();
    // Refresh every 5 minutes
    const interval = setInterval(fetchBriefing, 5 * 60 * 1000);
    return () => clearInterval(interval);
  }, [fetchBriefing]);

  return { ...data, meta, refreshBriefing: fetchBriefing };
}
